source 'https://cdn.cocoapods.org'

platform :ios, '18.0'

use_frameworks! :linkage => :static

target 'iosApp' do
  pod 'ComposeApp', :path => '../composeApp'

  pod 'FirebaseAuth'
  pod 'FirebaseCore'
  pod 'FirebaseDatabase'

  pod 'FirebaseDatabaseBridge',
      :path => './iosApp'

  pod 'FirebaseStorage'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '18.0'
    end
  end
end