name: ComposeApp .aab Build
run-name: Build signed .aab for ${{ github.ref_name }}

on:
  workflow_dispatch:
    inputs:
      build_env:
        description: 'Build environment'
        required: true
        default: 'release'
        type: choice
        options:
        - release

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.build_env }}
    steps:
        # Checkout code
        - uses: actions/checkout@v4

        # Setup JDK 17
        - uses: actions/setup-java@v4
          with:
            distribution: temurin
            java-version: '17'

        # Restore the google-services.json file, required for the "com.google.gms.google-services" plugin
        - name: Restore google-services.json
          run: echo "${GOOGLE_SERVICES_JSON}" | base64 -d > composeApp/google-services.json
          env:
            GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}

        # Setup Gradle
        - uses: gradle/actions/setup-gradle@v4

        # Grant execute permission for gradlew
        - name: Grant execute permission for gradlew
          run: chmod +x ./gradlew

        # Run unit tests before bundling
        - name: Run unit tests
          run: ./gradlew testDebugUnitTest --no-daemon

        # Restore upload.jks from base64 (stored in GitHub Secrets)
        - name: Restore Keystore
          run: echo "${KS_BASE64}" | base64 -d > "${GITHUB_WORKSPACE}/upload.jks"
          env:
            KS_BASE64: ${{ secrets.KS_BASE64 }}

        # Write keystore.properties file dynamically
        - name: Write keystore.properties
          run: |
            cat > keystore.properties <<'EOF'
            storeFile=${{ github.workspace }}/upload.jks
            storePassword=${{ secrets.KS_STORE_PASS }}
            keyAlias=${{ secrets.KS_ALIAS }}
            keyPassword=${{ secrets.KS_KEY_PASS }}
            EOF

        # Build signed release AAB
        - name: Gradle bundle
          run: ./gradlew :ComposeApp:clean :ComposeApp:bundle -PUSE_RELEASE_SIGNING=true

        # Upload AAB as artifact for download
        - name: Upload .aab artifact
          uses: actions/upload-artifact@v4
          with:
            name: composeApp-release-aab
            path: |
              **/build/outputs/bundle/release/*.aab
